In [2]:
import pandas as pd 
import numpy as np

In [36]:
tst = pd.read_csv('/data/APAproject/pre_qual/apatlas/human.PAS.txt', sep='\t')
tst

,PAS_ID,Chromosome,Position,Strand,Mean RPM,Intron/exon location,Ensemble ID,RefSeq Gene ID,Gene Symbol,Gene Name,FAMTOM ID,FANTOM Category,Extension,PAS_type,PSE,PAS Signal,Conservation,intergenic_TE
0,chr1:564599:+,chr1,564599,+,3.333397,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,49.53%,NoPAS,No,NO
1,chr1:564629:+,chr1,564629,+,1.201574,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,3.74%,NoPAS,No,NO
2,chr1:564664:+,chr1,564664,+,14.856402,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,4.67%,NoPAS,No,NO
3,chr1:564708:+,chr1,564708,+,1.872293,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,4.67%,NoPAS,No,NO
4,chr1:564952:+,chr1,564952,+,1.991760,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,YES,Pseudogene,32.71%,NoPAS,No,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311589,chrY:27546122:-,chrY,27546122,-,5.550364,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,11.21%,OtherPAS,No,YES
311590,chrY:28536584:-,chrY,28536584,-,1.619023,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,3.74%,AUUAAA,No,NO
311591,chrY:28548425:-,chrY,28548425,-,0.809998,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,6.54%,OtherPAS,No,YES
311592,chrY:28671979:-,chrY,28671979,-,0.985659,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,8.41%,Arich,No,NO
311593,chrY:28772221:-,chrY,28772221,-,11.041395,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,60.75%,AAUAAA,No,NO

In [3]:
tst['PAS_type'].value_counts()

Intron             78002
3'UTR(M)           76167
intergenic         61668
LncRNA(FANTOM5)    51535
3'UTR(F)           13623
3'UTR(L)           13623
CDS                 6717
Pseudogene          6257
3'UTR(S)            3158
5UTR                 844
Name: PAS_type, dtype: int64

In [37]:
# hg19_coordinates = pd.DataFrame([tst['Chromosome'], tst['Position'], tst['Position']])
hg19_coordinates = hg19_coordinates.T 
hg19_coordinates.to_csv('/data/APAproject/pre_qual/apatlas/PolyAdb_3_hg38_coordinates.bed', sep='\t' , index=False)

In [38]:
## ok read in the failed positions to get rid of them then read in the new positions to attach to the table

failed_positions = pd.read_csv('/data/APAproject/pre_qual/apatlas/failed_hg19_to_hg38_positions.bed', sep='\t')
failed_positions

   chromosome       pos1       pos2
0        chr1  120908277  120908277
1        chr1  120908277  120908277
2        chr1  147919834  147919834
3        chr1  149665879  149665879
4        chr1  150219070  150219070
..        ...        ...        ...
71       chrX  142582600  142582600
72       chrX  142723951  142723951
73       chrX  142715897  142715897
74       chrX  149574315  149574315
75       chrY   14919272   14919272

[76 rows x 3 columns]

In [39]:
failed_positions['pos1'] = failed_positions['pos1'].map(str)
failed_positions['identifier'] = failed_positions.chromosome.str.cat(failed_positions.pos1) 
failed_positions

   chromosome       pos1       pos2     identifier
0        chr1  120908277  120908277  chr1120908277
1        chr1  120908277  120908277  chr1120908277
2        chr1  147919834  147919834  chr1147919834
3        chr1  149665879  149665879  chr1149665879
4        chr1  150219070  150219070  chr1150219070
..        ...        ...        ...            ...
71       chrX  142582600  142582600  chrX142582600
72       chrX  142723951  142723951  chrX142723951
73       chrX  142715897  142715897  chrX142715897
74       chrX  149574315  149574315  chrX149574315
75       chrY   14919272   14919272   chrY14919272

[76 rows x 4 columns]

In [40]:
tst['pos1'] = tst['Position'].map(str)
tst['identifier'] = tst.Chromosome.str.cat(tst.pos1) 
tst

,PAS_ID,Chromosome,Position,Strand,Mean RPM,Intron/exon location,Ensemble ID,RefSeq Gene ID,Gene Symbol,Gene Name,FAMTOM ID,FANTOM Category,Extension,PAS_type,PSE,PAS Signal,Conservation,intergenic_TE,pos1,identifier
0,chr1:564599:+,chr1,564599,+,3.333397,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,49.53%,NoPAS,No,NO,564599,chr1564599
1,chr1:564629:+,chr1,564629,+,1.201574,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,3.74%,NoPAS,No,NO,564629,chr1564629
2,chr1:564664:+,chr1,564664,+,14.856402,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564664,chr1564664
3,chr1:564708:+,chr1,564708,+,1.872293,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564708,chr1564708
4,chr1:564952:+,chr1,564952,+,1.991760,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,YES,Pseudogene,32.71%,NoPAS,No,NO,564952,chr1564952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311589,chrY:27546122:-,chrY,27546122,-,5.550364,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,11.21%,OtherPAS,No,YES,27546122,chrY27546122
311590,chrY:28536584:-,chrY,28536584,-,1.619023,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,3.74%,AUUAAA,No,NO,28536584,chrY28536584
311591,chrY:28548425:-,chrY,28548425,-,0.809998,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,6.54%,OtherPAS,No,YES,28548425,chrY28548425
311592,chrY:28671979:-,chrY,28671979,-,0.985659,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,8.41%,Arich,No,NO,28671979,chrY28671979
311593,chrY:28772221:-,chrY,28772221,-,11.041395,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,60.75%,AAUAAA,No,NO,28772221,chrY28772221

In [41]:
poly_atlas = tst[~tst.identifier.isin(failed_positions.identifier.values)]
poly_atlas

,PAS_ID,Chromosome,Position,Strand,Mean RPM,Intron/exon location,Ensemble ID,RefSeq Gene ID,Gene Symbol,Gene Name,FAMTOM ID,FANTOM Category,Extension,PAS_type,PSE,PAS Signal,Conservation,intergenic_TE,pos1,identifier
0,chr1:564599:+,chr1,564599,+,3.333397,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,49.53%,NoPAS,No,NO,564599,chr1564599
1,chr1:564629:+,chr1,564629,+,1.201574,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,3.74%,NoPAS,No,NO,564629,chr1564629
2,chr1:564664:+,chr1,564664,+,14.856402,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564664,chr1564664
3,chr1:564708:+,chr1,564708,+,1.872293,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564708,chr1564708
4,chr1:564952:+,chr1,564952,+,1.991760,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,na,na,YES,Pseudogene,32.71%,NoPAS,No,NO,564952,chr1564952
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311589,chrY:27546122:-,chrY,27546122,-,5.550364,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,11.21%,OtherPAS,No,YES,27546122,chrY27546122
311590,chrY:28536584:-,chrY,28536584,-,1.619023,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,3.74%,AUUAAA,No,NO,28536584,chrY28536584
311591,chrY:28548425:-,chrY,28548425,-,0.809998,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,6.54%,OtherPAS,No,YES,28548425,chrY28548425
311592,chrY:28671979:-,chrY,28671979,-,0.985659,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,8.41%,Arich,No,NO,28671979,chrY28671979
311593,chrY:28772221:-,chrY,28772221,-,11.041395,intergenic,NaN,NaN,NaN,NaN,na,na,NO,intergenic,60.75%,AAUAAA,No,NO,28772221,chrY28772221

In [42]:
##read in the converted positions
hg38_coordinates = pd.read_csv('/data/APAproject/pre_qual/apatlas/hglft_genome_2be15_ea7880.bed', sep='\t')
hg38_coordinates

       Chromosome      pos1      pos2
0            chr1    629219    629219
1            chr1    629249    629249
2            chr1    629284    629284
3            chr1    629328    629328
4            chr1    629572    629572
...           ...       ...       ...
311513       chrY  25399975  25399975
311514       chrY  26390437  26390437
311515       chrY  26402278  26402278
311516       chrY  26525832  26525832
311517       chrY  26626074  26626074

[311518 rows x 3 columns]

In [45]:
poly_atlas['hg38_pos'] = hg38_coordinates['pos1'].values
poly_atlas

/home/aiden/anaconda3/envs/r_seurat/lib/python3.9/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

,PAS_ID,Chromosome,Position,Strand,Mean RPM,Intron/exon location,Ensemble ID,RefSeq Gene ID,Gene Symbol,Gene Name,...,FANTOM Category,Extension,PAS_type,PSE,PAS Signal,Conservation,intergenic_TE,pos1,identifier,hg38_pos
0,chr1:564599:+,chr1,564599,+,3.333397,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,...,na,NO,Pseudogene,49.53%,NoPAS,No,NO,564599,chr1564599,629219
1,chr1:564629:+,chr1,564629,+,1.201574,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,...,na,NO,Pseudogene,3.74%,NoPAS,No,NO,564629,chr1564629,629249
2,chr1:564664:+,chr1,564664,+,14.856402,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,...,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564664,chr1564664,629284
3,chr1:564708:+,chr1,564708,+,1.872293,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,...,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564708,chr1564708,629328
4,chr1:564952:+,chr1,564952,+,1.991760,Single exon,ENSG00000225972,na,MTND1P23,mitochondrially encoded NADH:ubiquinone oxidor...,...,na,YES,Pseudogene,32.71%,NoPAS,No,NO,564952,chr1564952,629572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311589,chrY:27546122:-,chrY,27546122,-,5.550364,intergenic,NaN,NaN,NaN,NaN,...,na,NO,intergenic,11.21%,OtherPAS,No,YES,27546122,chrY27546122,25399975
311590,chrY:28536584:-,chrY,28536584,-,1.619023,intergenic,NaN,NaN,NaN,NaN,...,na,NO,intergenic,3.74%,AUUAAA,No,NO,28536584,chrY28536584,26390437
311591,chrY:28548425:-,chrY,28548425,-,0.809998,intergenic,NaN,NaN,NaN,NaN,...,na,NO,intergenic,6.54%,OtherPAS,No,YES,28548425,chrY28548425,26402278
311592,chrY:28671979:-,chrY,28671979,-,0.985659,intergenic,NaN,NaN,NaN,NaN,...,na,NO,intergenic,8.41%,Arich,No,NO,28671979,chrY28671979,26525832
311593,chrY:28772221:-,chrY,28772221,-,11.041395,intergenic,NaN,NaN,NaN,NaN,...,na,NO,intergenic,60.75%,AAUAAA,No,NO,28772221,chrY28772221,26626074

In [50]:
poly_atlas.to_csv('/data/APAproject/pre_qual/apatlas/PolyA_db_v3_hg38_mapped.bed', sep='\t')

In [3]:
### lets read an example annotation table and map it to APA database
polyA_atlas = pd.read_csv('/data/APAproject/pre_qual/apatlas/PolyA_db_v3_hg38_mapped.bed', sep='\t')
peaks = pd.read_csv('/data1/APA/Paul_ALS_Data/sierra_out/ALS_paul_peaks_annotated.txt', sep='\t')
peaks

,seqnames,start,end,width,strand,gene_id,UTR3,UTR5,intron,exon,CDS,pA_motif,pA_stretch,pT_stretch,Junctions
ARGLU1:chr13:106543856-106557719:-1,chr13,106543856,106557719,13864,-,ARGLU1,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
DST:chr6:56699737-56852174:-1,chr6,56699737,56852174,152438,-,DST,NaN,YES,YES,YES,YES,False,False,False,across-junctions
TERF2IP:chr16:75647773-75657331:1,chr16,75647773,75657331,9559,+,TERF2IP,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
ZNF708:chr19:21293722-21309554:-1,chr19,21293722,21309554,15833,-,ZNF708,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
KMT2E:chr7:105014280-105062294:1,chr7,105014280,105062294,48015,+,KMT2E,NaN,YES,YES,YES,YES,False,False,False,across-junctions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TAS2R14:chr12:10948138-10948978:-1,chr12,10948138,10948978,841,-,"PRH1,TAS2R14",NaN,NaN,YES,NaN,NaN,False,False,False,no-junctions
PRH1:chr12:10948138-10948978:-1,chr12,10948138,10948978,841,-,"PRH1,TAS2R14",NaN,NaN,YES,NaN,NaN,False,False,False,no-junctions
ANK2:chr4:112982777-112983569:1,chr4,112982777,112983569,793,+,ANK2,NaN,NaN,YES,NaN,NaN,False,True,False,no-junctions
NBPF11:chr1:148127499-148128417:-1,chr1,148127499,148128417,919,-,NBPF11,NaN,NaN,YES,NaN,NaN,False,False,False,no-junctions
FNBP1:chr9:129920974-129922138:-1,chr9,129920974,129922138,1165,-,FNBP1,NaN,NaN,YES,NaN,NaN,False,False,False,no-junctions

In [3]:
peaks['width'].mean()

1603.3375839455884

In [13]:
peaks['width'].median()

444.0

In [4]:
max(peaks['width'])

1109956

In [5]:
min(peaks['width'])

5

In [9]:
min(peaks[peaks['UTR3']=='YES']['width'])

7

In [4]:
peaks[peaks['UTR3']=='YES']

,seqnames,start,end,width,strand,gene_id,UTR3,UTR5,intron,exon,CDS,pA_motif,pA_stretch,pT_stretch,Junctions
ARGLU1:chr13:106543856-106557719:-1,chr13,106543856,106557719,13864,-,ARGLU1,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
TERF2IP:chr16:75647773-75657331:1,chr16,75647773,75657331,9559,+,TERF2IP,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
ZNF708:chr19:21293722-21309554:-1,chr19,21293722,21309554,15833,-,ZNF708,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
KMT2E:chr7:105077148-105091364:1,chr7,105077148,105091364,14217,+,KMT2E,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
REX1BD:chr19:18589507-18592336:1,chr19,18589507,18592336,2830,+,REX1BD,YES,NaN,NaN,NaN,NaN,True,False,False,across-junctions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TMEM165:chr4:55425535-55426436:1,chr4,55425535,55426436,902,+,TMEM165,YES,NaN,NaN,NaN,NaN,False,False,False,no-junctions
YWHAB:chr20:44907620-44908280:1,chr20,44907620,44908280,661,+,YWHAB,YES,NaN,NaN,NaN,NaN,False,False,False,no-junctions
GOLGA8B:chr15:34525631-34526133:-1,chr15,34525631,34526133,503,-,GOLGA8B,YES,NaN,NaN,NaN,NaN,True,False,False,no-junctions
USP33:chr1:77711703-77715940:-1,chr1,77711703,77715940,4238,-,USP33,YES,NaN,NaN,NaN,NaN,False,False,False,across-junctions
LIFR:chr5:38476383-38477217:-1,chr5,38476383,38477217,835,-,LIFR,YES,NaN,NaN,NaN,NaN,False,False,False,no-junctions

In [16]:
peaks[peaks['UTR3']=='YES']['gene_id'].nunique()

13666

In [7]:
gene_counts = peaks['gene_id'].value_counts()
gene_counts[gene_counts > 1]

DLG2                          744
CADM2                         725
IL1RAPL1                      660
CNTNAP2                       630
CSMD1                         584
                             ...
ZNF467                          2
H2AFJ                           2
AC005871.2                      2
BACH1,BACH1-IT1,AP000240.1      2
BNIP1                           2
Name: gene_id, Length: 15636, dtype: int64

In [11]:
print('genes with one peak on their 3UTR.......', len(gene_counts[gene_counts == 1]))
print('genes with two peaks on their 3UTR.......',len(gene_counts[gene_counts == 2]))
print('genes with three peaks on their 3UTR.......',len(gene_counts[gene_counts == 3]))
print('genes with four peaks on their 3UTR.......',len(gene_counts[gene_counts == 4]))
print('genes with more than four peaks on their 3UTR.......',len(gene_counts[gene_counts > 4]))

genes with one peak on their 3UTR....... 4217
genes with two peaks on their 3UTR....... 2728
genes with three peaks on their 3UTR....... 1581
genes with four peaks on their 3UTR....... 1274
genes with more than four peaks on their 3UTR....... 10053

In [14]:
polyA_atlas

,Unnamed: 0,PAS_ID,Chromosome,Position,Strand,Mean RPM,Intron/exon location,Ensemble ID,RefSeq Gene ID,Gene Symbol,...,FANTOM Category,Extension,PAS_type,PSE,PAS Signal,Conservation,intergenic_TE,pos1,identifier,hg38_pos
0,0,chr1:564599:+,chr1,564599,+,3.333397,Single exon,ENSG00000225972,na,MTND1P23,...,na,NO,Pseudogene,49.53%,NoPAS,No,NO,564599,chr1564599,629219
1,1,chr1:564629:+,chr1,564629,+,1.201574,Single exon,ENSG00000225972,na,MTND1P23,...,na,NO,Pseudogene,3.74%,NoPAS,No,NO,564629,chr1564629,629249
2,2,chr1:564664:+,chr1,564664,+,14.856402,Single exon,ENSG00000225972,na,MTND1P23,...,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564664,chr1564664,629284
3,3,chr1:564708:+,chr1,564708,+,1.872293,Single exon,ENSG00000225972,na,MTND1P23,...,na,NO,Pseudogene,4.67%,NoPAS,No,NO,564708,chr1564708,629328
4,4,chr1:564952:+,chr1,564952,+,1.991760,Single exon,ENSG00000225972,na,MTND1P23,...,na,YES,Pseudogene,32.71%,NoPAS,No,NO,564952,chr1564952,629572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311513,311589,chrY:27546122:-,chrY,27546122,-,5.550364,intergenic,NaN,NaN,NaN,...,na,NO,intergenic,11.21%,OtherPAS,No,YES,27546122,chrY27546122,25399975
311514,311590,chrY:28536584:-,chrY,28536584,-,1.619023,intergenic,NaN,NaN,NaN,...,na,NO,intergenic,3.74%,AUUAAA,No,NO,28536584,chrY28536584,26390437
311515,311591,chrY:28548425:-,chrY,28548425,-,0.809998,intergenic,NaN,NaN,NaN,...,na,NO,intergenic,6.54%,OtherPAS,No,YES,28548425,chrY28548425,26402278
311516,311592,chrY:28671979:-,chrY,28671979,-,0.985659,intergenic,NaN,NaN,NaN,...,na,NO,intergenic,8.41%,Arich,No,NO,28671979,chrY28671979,26525832
311517,311593,chrY:28772221:-,chrY,28772221,-,11.041395,intergenic,NaN,NaN,NaN,...,na,NO,intergenic,60.75%,AAUAAA,No,NO,28772221,chrY28772221,26626074

## dist plotting the REDU for MAAPER outputs

In [52]:
import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
os.chdir('/data1/APA/Paul_ALS_Data/bams_in/subscelltype_bamfiles/Mapper_outs/')

In [43]:
CTs = [ct for ct in os.listdir() if 'CTRL' in ct]
CTs = list(set(CTs))
CTs

['AST-FB_sALSvsCTRL',
 'IN-VIP_C9ALSvsCTRL',
 'Oligodendrocytes_sALSvsCTRL',
 'IN-SST_C9ALSvsCTRL',
 'Excitatory_sALSvsCTRL',
 'L2-3_C9ALSvsCTRL',
 'AST-FB_C9ALSvsCTRL',
 'L4_C9ALSvsCTRL',
 'Inhibitory_sALSvsCTRL',
 'L2-3_sALSvsCTRL',
 'L5-6_C9ALSvsCTRL',
 'Endothelial_ALSvsCTRL',
 'AST-PP_sALSvsCTRL',
 'L5-6-CC_sALSvsCTRL',
 'L5-6-CC_C9ALSvsCTRL',
 'L4_sALSvsCTRL',
 'OPC_sALSvsCTRL',
 'IN-VIP_sALSvsCTRL',
 'IN-PV_C9ALSvsCTRL',
 'IN-SST_sALSvsCTRL',
 'AST-PP_C9ALSvsCTRL',
 'IN-PV_sALSvsCTRL',
 'Microglia_sALSvsCTRL',
 'Excitatory_C9ALSvsCTRL',
 'OPC_C9ALSvsCTRL',
 'Oligodendrocytes_C9ALSvsCTRL',
 'Microglia_C9ALSvsCTRL',
 'Inhibitory_C9ALSvsCTRL']

In [2]:
exc_df = pd.read_csv('Excitatory_C9ALSvsCTRL/gene.txt', sep='\t')
exc_df

,gene,npas,pval,RLDu,RLDi,REDu,REDu.pval,REDi,REDi.pval,nread.c1.1,nread.c1.2,nread.c1.3,nread.c1.4,nread.c1.5,nread.c2.1,nread.c2.2,nread.c2.3,nread.c2.4,nread.c2.5
0,B3GALT6,2,0.000002,1.600,NaN,2.720,6.070000e-07,NaN,NaN,0,72,0,0,0,0,0,0,63,0
1,PUSL1,4,0.130000,0.212,NaN,0.964,1.220000e-02,NaN,NaN,37,193,0,0,88,79,0,40,125,0
2,MIB2,2,0.003960,NaN,0.917,NaN,NaN,0.917,1.150000e-03,61,315,0,0,327,467,75,384,931,0
3,PRKCZ,4,0.003760,-0.334,0.641,-0.564,1.610000e-02,0.836,2.510000e-08,170,589,0,105,491,488,57,446,848,29
4,SKI,5,0.394000,-0.143,-0.228,-0.556,5.310000e-02,0.177,6.460000e-01,34,150,0,34,162,293,34,126,220,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9250,LAGE3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,264,0,49,0,0,0,0,134,0
9251,FAM3A,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,105,0,0,36,30,0,31,42,0
9252,G6PD,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,45,0,0,31,45,0,4,58,0
9253,MPP1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34,159,0,0,93,79,0,45,133,0
9254,RAB39B,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,92,0,0,79,81,0,68,41,0

In [120]:
def plot_redu(df, name):
    dat = df['REDu']
    dat.replace([np.inf, -np.inf], np.nan, inplace=True)
    dat.dropna(inplace=True)
    ax = sns.distplot(dat)
    ax.set(xlabel='REDu', ylabel='Density')
    plt.axvline(dat.median(),
                color='red', label=round(dat.median(),2))
    plt.legend()
    outname = "REDU_plots/" + name + '_REDu_distplots.png'
    plt.savefig(outname)
    plt.clf()

In [121]:
for ct_cn in CTs:
    file = ct_cn + "/gene.txt"
    df = pd.read_csv(file, sep='\t')
    print(ct_cn)
    print(df.shape)
    plot_redu(df, ct_cn)

AST-FB_sALSvsCTRL
(983, 11)
IN-VIP_C9ALSvsCTRL
(7381, 18)
Oligodendrocytes_sALSvsCTRL
(11532, 18)
IN-SST_C9ALSvsCTRL
(6432, 20)
Excitatory_sALSvsCTRL
(4928, 16)
L2-3_C9ALSvsCTRL
(8735, 13)
AST-FB_C9ALSvsCTRL
(1583, 14)
L4_C9ALSvsCTRL
(3968, 13)
Inhibitory_sALSvsCTRL
(8511, 18)
L2-3_sALSvsCTRL
(2183, 13)
L5-6_C9ALSvsCTRL
(413, 11)
Endothelial_ALSvsCTRL
(127, 11)
AST-PP_sALSvsCTRL
(11450, 16)
L5-6-CC_sALSvsCTRL
(106, 11)
L5-6-CC_C9ALSvsCTRL
(151, 11)
L4_sALSvsCTRL
(1698, 11)
OPC_sALSvsCTRL
(9013, 15)
IN-VIP_sALSvsCTRL
(2836, 14)
IN-PV_C9ALSvsCTRL
(5089, 19)
IN-SST_sALSvsCTRL
(5022, 16)
AST-PP_C9ALSvsCTRL
(11007, 21)
IN-PV_sALSvsCTRL
(4253, 14)
Microglia_sALSvsCTRL
(6241, 18)
Excitatory_C9ALSvsCTRL
(9255, 19)
OPC_C9ALSvsCTRL
(9774, 19)
Oligodendrocytes_C9ALSvsCTRL
(12012, 21)
Microglia_C9ALSvsCTRL
(6917, 21)
Inhibitory_C9ALSvsCTRL
(10400, 21)

In [98]:
dat.median()

-0.8879999999999999